module.exports = function (sequelize, DataTypes) {
    return sequelize.define('madlib', {
        keyphrase: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        owner: {
            type: DataTypes.INTEGER,
            allowNull: false,
        },
        noun1: DataTypes.STRING,
        noun2: DataTypes.STRING,
        noun3: DataTypes.STRING,
        noun4: DataTypes.STRING,
        adj1: DataTypes.STRING,
        adj2: DataTypes.STRING,
        adj3: DataTypes.STRING,
        adj4: DataTypes.STRING,
        adj5: DataTypes.STRING,
        adj6: DataTypes.STRING,
        verb1: DataTypes.STRING,
        verb2: DataTypes.STRING,
        verb3: DataTypes.STRING,
        verb4: DataTypes.STRING,
        verb5: DataTypes.STRING,
        adverb: DataTypes.STRING,
        famMem1: DataTypes.STRING,
        famMem2: DataTypes.STRING,
        famMem3: DataTypes.STRING,
        PTverb1: DataTypes.STRING,
        PTverb2: DataTypes.STRING,
        quote: DataTypes.STRING,
        PLnoun1: DataTypes.STRING,
        PLnoun2: DataTypes.STRING,
        PLnoun3: DataTypes.STRING,
        PLnoun4: DataTypes.STRING,
        ingVerb: DataTypes.STRING,
        liquid: DataTypes.STRING,
        container: DataTypes.STRING,
        vehicle: DataTypes.STRING,
        occupation: DataTypes.STRING,
        food1: DataTypes.STRING,
        food2: DataTypes.STRING,
        building: DataTypes.STRING,
        number1: DataTypes.STRING,
        number2: DataTypes.STRING,
        number3: DataTypes.STRING,
        number4: DataTypes.STRING,
        room: DataTypes.STRING,
        animal: DataTypes.STRING,
        shape: DataTypes.STRING,
        bodypart: DataTypes.STRING,
        name: DataTypes.STRING,
        location: DataTypes.STRING
    });
};